### ISSUE TITLE
Append instruction to Getting started

### ISSUE THREAD

**Issue by LawsonGu** [genesys-neu/ni-rf-data-recording-api#4]
In https://github.com/genesys-neu/ni-rf-data-recording-api/blob/main/docs/Getting_Started_Guide_of_NI_RF_Data_Recording_API.pdf Page 4, I suggest add below content.
![image](https://user-images.githubusercontent.com/101655210/205562731-c5278460-c4fc-434b-a0be-f46eceb98247.png)

I have tested, guide along with the Getting_Started_Guide_of_NI_RF_Data_Recording_API.pdf(In a brand new Ubuntu20.04). Error prompted:
![image](https://user-images.githubusercontent.com/101655210/205562510-2a0f63b1-7b83-40ba-9354-baed7aa087fa.png)
Actually, this is because the python file in /usr/bin not linked to Python3.9.
So it needs a change(apped instruction to fix that link) for a better guide to users.

**Comment by mauro-belgiovine** [comment]
Hi, thanks for your comment. @Abdo-Gaber any chance we can include this information in the Getting Started Guide pdf?
